apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: news-app
  type: NodePort
  ports:
  - name: news-app-service-port
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31111